# Generated by Django 4.2.20 on 2025-03-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default='🏠', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='icon',
            field=models.CharField(blank=True, default='👤', max_length=10),
        ),
    ]
