# Generated by Django 4.2.20 on 2025-03-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_icon_groupmember_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
