# Generated by Django 4.2.20 on 2025-03-27 02:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_receipt_receiptitem_receiptitemsplit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='split_method',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='split_user',
        ),
        migrations.AddField(
            model_name='receipt',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptitemsplit',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_item_payments', to='api.groupmember'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_due', to='api.groupmember')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_owed', to='api.groupmember')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='api.group')),
            ],
            options={
                'unique_together': {('group', 'debtor', 'creditor')},
            },
        ),
    ]
