# Generated by Django 4.2.20 on 2025-04-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_receiptitem_split_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
