# Generated by Django 4.2.20 on 2025-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shoppinglistitem_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['position', 'added_at']},
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
