from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import (
    SignupView,
    GroupCreateView,
    GroupJoinView,
    UserGroupsView,
    GroupMembersView,
    GroupWithdrawView,
    ShoppingListCreateView,
    ShoppingListView,
    ShoppingListItemCreateView,
    ShoppingListItemToggleView,
    ShoppingListDelete,
    ShoppingListItemDelete,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    ReceiptPreviewView,
    ReceiptConfirmView,
    ReceiptSplitsView,
    GroupDebtsView,
    GroupMonthlyExpensesView,
    DashboardView,
    CalendarExpensesView,
    MyExpenseDetailsView,
    PayDebtView,
    HistoryView,
    OtherExpenseDetailsView,
    MyExpenseDetailsByDateView,
    ShoppingListItemReorderView,
    ShoppingListReorderView,
    ShoppingListItemUpdateView,
)

router = DefaultRouter()

urlpatterns = [
    path('', include(router.urls)),
    path('auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/signup/', SignupView.as_view(), name='signup'),
    
    path('groups/create/', GroupCreateView.as_view(), name='group_create'),
    path('groups/join/', GroupJoinView.as_view(), name='group_join'),
    path('groups/my-groups/', UserGroupsView.as_view(), name='user_groups'),
    path('groups/<uuid:group_id>/members/', GroupMembersView.as_view(), name='group_members'),
    path('groups/withdraw/', GroupWithdrawView.as_view(), name='group_withdraw'),
    path('groups/<uuid:group_id>/receipts/preview/', ReceiptPreviewView.as_view(), name='receipt-preview'),
    path('groups/<uuid:group_id>/receipts/confirm/',ReceiptConfirmView.as_view(), name='receipt-confirm'),
    path('groups/<uuid:group_id>/receipts/<uuid:receipt_id>/splits/', ReceiptSplitsView.as_view(), name='receipt-splits'),
    path('groups/<uuid:group_id>/debts/', GroupDebtsView.as_view(), name='group-debts'),
    path('groups/<uuid:group_id>/expenses/<int:year>/<int:month>/', GroupMonthlyExpensesView.as_view(), name='group-monthly-expenses'),
    path('groups/<uuid:group_id>/dashboard/', DashboardView.as_view(), name='dashboard'),
    path('groups/<uuid:group_id>/calendar/<int:year>/<int:month>/', CalendarExpensesView.as_view(), name='calendar-expenses'),
    path('groups/<uuid:group_id>/my-expenses/details/', MyExpenseDetailsView.as_view(), name='my-expense-details'),
    path('groups/<uuid:group_id>/my-expenses/by-date/', MyExpenseDetailsByDateView.as_view(), name='my-expense-details-by-date'),
    path('groups/<uuid:group_id>/other-expenses/<uuid:member_id>/details/',OtherExpenseDetailsView.as_view(), name='my-expense-details'),
    path('groups/<uuid:group_id>/debts/<uuid:debt_id>/pay/', PayDebtView.as_view(), name='pay-debt'),
    path('groups/<uuid:group_id>/history/', HistoryView.as_view(), name='history'),
    
    path('shopping-lists/create/', ShoppingListCreateView.as_view(), name='shopping_list_create'),
    path('shopping-lists/<uuid:group_id>/', ShoppingListView.as_view(), name='shopping_list_view'),
    path('shopping-lists/<uuid:list_id>/delete/', ShoppingListDelete.as_view(), name='shopping_list_delete'),
    path('shopping-list-items/create/', ShoppingListItemCreateView.as_view(), name='shopping_list_item_create'),
    path('shopping-list-items/<uuid:item_id>/toggle/', ShoppingListItemToggleView.as_view(), name='shopping_list_item_toggle'),
    path('shopping-list-items/<uuid:item_id>/delete/', ShoppingListItemDelete.as_view(), name='shopping_list_item_delete'),
    path('shopping-lists/<str:shopping_list_id>/reorder/', ShoppingListItemReorderView.as_view(), name='shopping_list_reorder'),
    path('shopping-lists/<uuid:group_id>/reorderlist/', ShoppingListReorderView.as_view(), name='shopping_list_reorder'),
    path('shopping-list-items/<uuid:item_id>/update/', ShoppingListItemUpdateView.as_view(), name='shopping_list_item_update'),

    path('categories/<uuid:group_id>/', CategoryListView.as_view(), name='category_list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/<uuid:category_id>/update/', CategoryUpdateView.as_view(), name='category_update'),
]
